### ISSUE TITLE
The NMAP-Process accepts invalid targets

### ISSUE THREAD

**Issue by Trosky** [secureCodeBox/engine#15]
**Describe the bug**
You can pass invalid target parameters to the nmap process form.

**To Reproduce**
1. Go to 'NMAP Scan Process'
2. Add  'http://scanme.nmap.org' as target
3. Start the process
4. See error results of the container

``` 
scanner-infrastructure-nmap_1     | Started working on Job "f024bec9-75f4-11e8-84ea-0242ac120004"
scanner-infrastructure-nmap_1     | SCANNING 1 locations
scanner-infrastructure-nmap_1     | SCANNING location: http://scanme.nmap.org, parameters:
scanner-infrastructure-nmap_1     | Unable to split netmask from target expression: "http://scanme.nmap.org"
scanner-infrastructure-nmap_1     | WARNING: No targets were specified, so 0 hosts scanned.
scanner-infrastructure-nmap_1     | 
scanner-infrastructure-nmap_1     | Failed to perform Job "f024bec9-75f4-11e8-84ea-0242ac120004" Error: Failed to execute nmap portscan.
scanner-infrastructure-nmap_1     |     at ScannerScaffolding.worker [as _worker] (/src/src/nmap.js:81:19)
scanner-infrastructure-nmap_1     |     at <anonymous>
scanner-infrastructure-nmap_1     |     at process._tickCallback (internal/process/next_tick.js:188:7)
```
**ToDo**
Implement validation.

**Comment by J12934** [comment]
Resolved by PR #17.
